apiVersion: flux-framework.org/v1alpha1
kind: MiniCluster
metadata:
  name: flux-sample
  namespace: flux-operator
spec:
  size: 2

  # If we don't set this, we won't be able to go above two!
  maxSize: 10

  # Interactive will start the broker to shell into
  interactive: true

  # This is a list because a pod can support multiple containers
  containers:
    - image: ghcr.io/rse-ops/singularity:tag-mamba
      workingDir: /data

      # You can shell in to connect to the broker and issue commands that use CPU
      command: sleep infinity

      # Important! We need to have resource requests for the horizonal autoscaler
      # The Flux Operator doesn't know you want to use it, so it's up to you
      # to provide these if your metric is about CPU
      resources:
        limits:
          cpu: "1"

        requests:
          cpu: "1"

      fluxUser:
        name: fluxuser