apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  size: 2

  # If we don't set this, we won't be able to go above two!
  maxSize: 10

  # Interactive will start the broker to shell into
  interactive: true

  # This is a list because a pod can support multiple containers
  containers:
    - image: rockylinux:9
      workingDir: /data

      # Important! We need to have resource requests for the horizonal autoscaler
      # The Flux Operator doesn't know you want to use it, so it's up to you
      # to provide these if your metric is about CPU
      resources:
        limits:
          cpu: "1"

        requests:
          cpu: "1"