# Run this from this directory!
# kind create cluster -f kind-config.yaml
# kubectl apply -f ./examples/dist/flux-operator.yaml
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
 - role: control-plane
   image: kindest/node:v1.27.0
   extraMounts:
    - hostPath: "."
      containerPath: /tmp/workflow

   # This ensures we can see our NodePort for nginx
   extraPortMappings:
    - containerPort: 30093
      hostPort: 30093
      listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0",
      # protocol defaults to tcp

 - role: worker
   image: kindest/node:v1.27.0