apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: flux-operator
data:
  flux.conf: |
    server {
        listen       80;
        server_name  localhost;

        # This is an example of service a static site
        location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
        }        
        # This is an example of forwarding traffic to somewhere else
        # location / {
        #  proxy_pass http://google.com;
        # }
        # And You could do other things here, like provide an internal service
        # that can connect to the
        # http://flux-sample-0.flux-service.flux-operator.svc.cluster.local:5000;
    }
