apiVersion: flux-framework.org/v1alpha1
kind: MiniCluster
metadata:
  name: flux-sample
  namespace: flux-operator
spec:

  size: 4

  # We have a lot of examples to try - easy to do interactively

  interactive: true
  # This is created with the kind-config.yaml
  # You should only need to pull once (the container is pulled to bound volume)
  volumes:
    data:
      storageClass: hostpath
      path: /tmp/workflow

  # This is a list because a pod can support multiple containers
  containers:
    - image: ghcr.io/rse-ops/singularity:tag-mamba
      workingDir: /tmp/workflow
      commands:
         pre: |
           pip install foundry_ml
           conda install -c conda-forge scikit-learn scikit-image
           pip install keras-unet seaborn pandas pymatgen matminer opencv-python \
              tables tensorflow matplotlib

      fluxUser:
        name: fluxuser

      # Container will be pre-pulled here only by the broker
      volumes:
        data:
          path: /tmp/workflow
       
      # Running a container in a container
      securityContext:
        privileged: true