"""
    fluxoperator

    Python SDK for Flux-Operator  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fluxoperator
from fluxoperator.model.v1_condition import V1Condition
globals()['V1Condition'] = V1Condition
from fluxoperator.model.api_v1alpha1_mini_cluster_status import ApiV1alpha1MiniClusterStatus


class TestApiV1alpha1MiniClusterStatus(unittest.TestCase):
    """ApiV1alpha1MiniClusterStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV1alpha1MiniClusterStatus(self):
        """Test ApiV1alpha1MiniClusterStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiV1alpha1MiniClusterStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
