"""
    fluxoperator

    Python SDK for Flux-Operator  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fluxoperator
from fluxoperator.model.k8s_io_apimachinery_pkg_apis_meta_v1_condition import K8sIoApimachineryPkgApisMetaV1Condition
globals()['K8sIoApimachineryPkgApisMetaV1Condition'] = K8sIoApimachineryPkgApisMetaV1Condition
from fluxoperator.model.mini_cluster_status import MiniClusterStatus


class TestMiniClusterStatus(unittest.TestCase):
    """MiniClusterStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMiniClusterStatus(self):
        """Test MiniClusterStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MiniClusterStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
