"""
    fluxoperator

    Python SDK for Flux-Operator  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fluxoperator
from fluxoperator.model.api_v1alpha1_mini_cluster_spec import ApiV1alpha1MiniClusterSpec
from fluxoperator.model.api_v1alpha1_mini_cluster_status import ApiV1alpha1MiniClusterStatus
from fluxoperator.model.v1_object_meta import V1ObjectMeta
globals()['ApiV1alpha1MiniClusterSpec'] = ApiV1alpha1MiniClusterSpec
globals()['ApiV1alpha1MiniClusterStatus'] = ApiV1alpha1MiniClusterStatus
globals()['V1ObjectMeta'] = V1ObjectMeta
from fluxoperator.model.api_v1alpha1_mini_cluster import ApiV1alpha1MiniCluster


class TestApiV1alpha1MiniCluster(unittest.TestCase):
    """ApiV1alpha1MiniCluster unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV1alpha1MiniCluster(self):
        """Test ApiV1alpha1MiniCluster"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiV1alpha1MiniCluster()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
