"""
    fluxoperator

    Python SDK for Flux-Operator  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fluxoperator
from fluxoperator.model.api_v1alpha1_mini_cluster_volume import ApiV1alpha1MiniClusterVolume


class TestApiV1alpha1MiniClusterVolume(unittest.TestCase):
    """ApiV1alpha1MiniClusterVolume unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV1alpha1MiniClusterVolume(self):
        """Test ApiV1alpha1MiniClusterVolume"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiV1alpha1MiniClusterVolume()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
