"""
    fluxoperator

    Python SDK for Flux-Operator  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fluxoperator
from fluxoperator.model.commands import Commands
from fluxoperator.model.container_resources import ContainerResources
from fluxoperator.model.container_volume import ContainerVolume
from fluxoperator.model.flux_user import FluxUser
from fluxoperator.model.life_cycle import LifeCycle
globals()['Commands'] = Commands
globals()['ContainerResources'] = ContainerResources
globals()['ContainerVolume'] = ContainerVolume
globals()['FluxUser'] = FluxUser
globals()['LifeCycle'] = LifeCycle
from fluxoperator.model.mini_cluster_container import MiniClusterContainer


class TestMiniClusterContainer(unittest.TestCase):
    """MiniClusterContainer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMiniClusterContainer(self):
        """Test MiniClusterContainer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MiniClusterContainer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
