"""
    fluxoperator

    Python SDK for Flux-Operator  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fluxoperator
from fluxoperator.model.k8s_io_apimachinery_pkg_util_intstr_int_or_string import K8sIoApimachineryPkgUtilIntstrIntOrString
globals()['K8sIoApimachineryPkgUtilIntstrIntOrString'] = K8sIoApimachineryPkgUtilIntstrIntOrString
from fluxoperator.model.pod_spec import PodSpec


class TestPodSpec(unittest.TestCase):
    """PodSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPodSpec(self):
        """Test PodSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PodSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
