"""
    fluxoperator

    Python SDK for Flux-Operator  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fluxoperator
from fluxoperator.model.api_v1alpha1_flux_user import ApiV1alpha1FluxUser


class TestApiV1alpha1FluxUser(unittest.TestCase):
    """ApiV1alpha1FluxUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV1alpha1FluxUser(self):
        """Test ApiV1alpha1FluxUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiV1alpha1FluxUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
