"""
    fluxoperator

    Python SDK for Flux-Operator  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fluxoperator
from fluxoperator.model.api_v1alpha1_mini_cluster import ApiV1alpha1MiniCluster
from fluxoperator.model.v1_list_meta import V1ListMeta
globals()['ApiV1alpha1MiniCluster'] = ApiV1alpha1MiniCluster
globals()['V1ListMeta'] = V1ListMeta
from fluxoperator.model.api_v1alpha1_mini_cluster_list import ApiV1alpha1MiniClusterList


class TestApiV1alpha1MiniClusterList(unittest.TestCase):
    """ApiV1alpha1MiniClusterList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV1alpha1MiniClusterList(self):
        """Test ApiV1alpha1MiniClusterList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiV1alpha1MiniClusterList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
