"""
    fluxoperator

    Python SDK for Flux-Operator  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fluxoperator
from fluxoperator.model.logging_spec import LoggingSpec


class TestLoggingSpec(unittest.TestCase):
    """LoggingSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoggingSpec(self):
        """Test LoggingSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LoggingSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
