"""
    fluxoperator

    Python SDK for Flux-Operator  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fluxoperator
from fluxoperator.model.mini_cluster_user import MiniClusterUser


class TestMiniClusterUser(unittest.TestCase):
    """MiniClusterUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMiniClusterUser(self):
        """Test MiniClusterUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MiniClusterUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
