"""
    fluxoperator

    Python SDK for Flux-Operator  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fluxoperator
from fluxoperator.model.flux_user import FluxUser


class TestFluxUser(unittest.TestCase):
    """FluxUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFluxUser(self):
        """Test FluxUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FluxUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
