"""
    fluxoperator

    Python SDK for Flux-Operator  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fluxoperator
from fluxoperator.model.k8s_io_apimachinery_pkg_util_intstr_int_or_string import K8sIoApimachineryPkgUtilIntstrIntOrString
globals()['K8sIoApimachineryPkgUtilIntstrIntOrString'] = K8sIoApimachineryPkgUtilIntstrIntOrString
from fluxoperator.model.api_v1alpha1_pod_spec import ApiV1alpha1PodSpec


class TestApiV1alpha1PodSpec(unittest.TestCase):
    """ApiV1alpha1PodSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV1alpha1PodSpec(self):
        """Test ApiV1alpha1PodSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiV1alpha1PodSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
