"""
    fluxoperator

    Python SDK for Flux-Operator  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fluxoperator
from fluxoperator.model.api_v1alpha1_flux_restful import ApiV1alpha1FluxRestful


class TestApiV1alpha1FluxRestful(unittest.TestCase):
    """ApiV1alpha1FluxRestful unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV1alpha1FluxRestful(self):
        """Test ApiV1alpha1FluxRestful"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiV1alpha1FluxRestful()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
