#!/bin/sh

# This waiting script is run continuously and only updates
# hosts and runs the job (breaking from the while) when 
# update_hosts.sh has been populated. This means the pod usually
# needs to be updated with the config map that has ips!

# We determine the update_hosts.sh is ready when it has content
count_lines() {
	lines=$(cat /flux_operator/update_hosts.sh | wc -l)
	echo $lines
}

while [ $(count_lines) -lt 2 ];
do
    echo "Host updating script not available yet, waiting..."
    sleep 5s
done             

# Run to discover hosts
/bin/sh /flux_operator/update_hosts.sh

# Show host updates
cat /etc/hosts

# Main host <name>-0
mainHost="%s"

printf "\n👋 Hello, I'm $(hostname)\n"
printf "The main host is ${mainHost}\n"

# These actions need to happen on all hosts
# Configure resources
mkdir -p /etc/flux/system

# --cores=IDS Assign cores with IDS to each rank in R, so we  assign 1-N to 0
flux R encode --hosts=%s --cores=%s > /etc/flux/system/R
printf "\n📦 Resources\n"
cat /etc/flux/system/R

mkdir -p /etc/flux/imp/conf.d/
cat <<EOT >> /etc/flux/imp/conf.d/imp.toml
[exec]
allowed-users = [ "flux", "root" ]
allowed-shells = [ "/usr/libexec/flux/flux-shell" ]	
EOT

printf "\n🦊 Independent Minister of Privilege\n"
cat /etc/flux/imp/conf.d/imp.toml

# Add a flux user (required)
useradd flux || printf "flux user already exists\n"

# Generate curve certificate (only need one shared)
if [ $(hostname) == "${mainHost}" ]; then
    printf "\n✨ Curve certificate being generated by $(hostname)\n"
    sudo -u flux flux keygen /mnt/curve/curve.cert
    cat /mnt/curve/curve.cert

    # Each node needs same munge key
    cp /etc/munge/munge.key /mnt/curve/munge.key

    # Start flux with the original entrypoint
    printf "\n🌀 flux start -o --config /etc/flux/config $@\n"
    flux start -o --config /etc/flux/config $@
    # Can we show some debug output (perhaps we can have a variable?)
    # How can we be sure it ran on all nodes?
else

    # Wait for main node to copy over its key
    while [ ! -f /mnt/curve/munge.key ];
    do
        printf "Shared munge key not available yet, waiting...\n"
        sleep 5s
    done
    cp /mnt/curve/munge.key /etc/munge/munge.key
    printf "\n🐸 flux start -o --config /etc/flux/config $@\n"
    flux start -o --config /etc/flux/config $@
    # should this be a sleep infinity instead?
    # flux start -o --config /etc/flux/config sleep infinity
fi
