apiVersion: flux-framework.org/v1alpha1
kind: MiniCluster
metadata:
  name: flux-sample
  namespace: flux-operator
spec:
  size: 4
  tasks: 2

  logging:
    strict: false

  volumes:
    data:
      storageClass: hostpath
      path: /tmp/data
      labels:
        type: "local"

  containers:
    - image: vanessa/molecular-design-parsl:latest
      cores: 2
      workingDir: /workflow
      launcher: true

      # Calculating workers as 4 nodes X 2 cpu
      command: /bin/bash ./scripts/run_0.sh --outdir /workflow --workers 8

      # Custom flux user
      fluxUser: 
        name: fluxuser

      commands:
        pre: |
          export LD_LIBRARY_PATH=/opt/conda/lib
          sudo chown -R /data fluxuser
          rm -rf ./runinfo
        postBroker: |
          cp /workflow/training-data-vs-time.svg /data/training-data-vs-time.svg
          cp /workflow/parsl-results.csv /data/parsl-results.csv
      volumes:
        data:
          path: /data