apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  size: 4
  tasks: 2

  logging:
    strict: false

  # kubectl apply -f ./examples/launchers/parsl/molecular-design/minicluster.yaml
  containers:
    - image: ghcr.io/rse-ops/molecular-design-parsl:tag-mamba
      workingDir: /workflow
      launcher: true

      # Calculating workers as 4 nodes X 2 cpu
      command: /bin/bash ./scripts/run_0.sh --outdir /workflow --workers 8
      commands:
        pre: |
          export LD_LIBRARY_PATH=/opt/conda/lib
        post: |
          cp /workflow/training-data-vs-time.svg /data/training-data-vs-time.svg
          cp /workflow/parsl-results.csv /data/parsl-results.csv
      volumes:
        data:
          path: /data
          hostPath: /data
