apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  size: 2

  # This starts the flux broker without a command (interactive)
  interactive: true
  flux:
    optionFlags: "-ompi=openmpi@5"

  containers:
    - image: ghcr.io/rse-ops/pokemon:app-latest
      