apiVersion: flux-framework.org/v1alpha1
kind: MiniCluster
metadata:
  name: flux-sample
  namespace: flux-operator
spec:

  # Number of pods to create for MiniCluster
  size: 2

  # This starts the flux broker without a command (interactive)
  interactive: true

  # This is a list because a pod can support multiple containers
  containers:
    - image: ghcr.io/rse-ops/pokemon:app-latest
      fluxOptionFlags: "-ompi=openmpi@5"
