# Source: s3-otomount/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: s3-mounter
  name: otomount-mounter
  namespace: otomount
spec:
  selector:
    matchLabels: 
      app: otomount-mounter
  template:
    metadata:
      labels:
        app: otomount-mounter
    spec:
      serviceAccountName: s3-mounter
      containers:
      - name: mounter 
        image: otomato/goofys 

        # We aren't certain all these flags are required
        command: ["./goofys", "-o", "allow_other", "-o", "nosuid", "--file-mode", "0777", "--dir-mode", "0777", "--uid", "0", "--gid", "0", "-f", "flux-operator-storage", "/var/s3"]        
        securityContext:
          privileged: true
        volumeMounts:
        - name: mntdatas3
          mountPath: /var/s3:shared
        env:
          - name: S3_BUCKET

            # This is our bucket name
            value: flux-operator-storage

           # And the mount path - this is the path from storage to the kubernetes node
           # This is the last argument of goofys
          - name: MOUNT_PATH
            value: /var/s3
      volumes:
      - name: mntdatas3
        hostPath:
          # This will be the path from the Kuberentes node to your pod! It MUST be in /tmp to allow cleanup
          path: /tmp/data
