# coding: utf-8

"""
    fluxoperator

    Python SDK for Flux-Operator

    The version of the OpenAPI document: v1alpha2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluxoperator.models.toleration import Toleration

class TestToleration(unittest.TestCase):
    """Toleration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Toleration:
        """Test Toleration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Toleration`
        """
        model = Toleration()
        if include_optional:
            return Toleration(
                effect = '',
                key = '',
                operator = '',
                value = ''
            )
        else:
            return Toleration(
        )
        """

    def testToleration(self):
        """Test Toleration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
