# coding: utf-8

"""
    fluxoperator

    Python SDK for Flux-Operator

    The version of the OpenAPI document: v1alpha2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluxoperator.models.pod_security_context import PodSecurityContext

class TestPodSecurityContext(unittest.TestCase):
    """PodSecurityContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PodSecurityContext:
        """Test PodSecurityContext
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PodSecurityContext`
        """
        model = PodSecurityContext()
        if include_optional:
            return PodSecurityContext(
                sysctls = {
                    'key' : ''
                    }
            )
        else:
            return PodSecurityContext(
        )
        """

    def testPodSecurityContext(self):
        """Test PodSecurityContext"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
