"""
    fluxoperator

    Python SDK for Flux-Operator  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from fluxoperator.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)

def lazy_import():
    from fluxoperator.model.api_v1alpha1_flux_restful import ApiV1alpha1FluxRestful
    from fluxoperator.model.api_v1alpha1_logging_spec import ApiV1alpha1LoggingSpec
    from fluxoperator.model.api_v1alpha1_mini_cluster_container import ApiV1alpha1MiniClusterContainer
    from fluxoperator.model.api_v1alpha1_mini_cluster_user import ApiV1alpha1MiniClusterUser
    from fluxoperator.model.api_v1alpha1_mini_cluster_volume import ApiV1alpha1MiniClusterVolume
    from fluxoperator.model.api_v1alpha1_pod_spec import ApiV1alpha1PodSpec
    globals()['ApiV1alpha1FluxRestful'] = ApiV1alpha1FluxRestful
    globals()['ApiV1alpha1LoggingSpec'] = ApiV1alpha1LoggingSpec
    globals()['ApiV1alpha1MiniClusterContainer'] = ApiV1alpha1MiniClusterContainer
    globals()['ApiV1alpha1MiniClusterUser'] = ApiV1alpha1MiniClusterUser
    globals()['ApiV1alpha1MiniClusterVolume'] = ApiV1alpha1MiniClusterVolume
    globals()['ApiV1alpha1PodSpec'] = ApiV1alpha1PodSpec


class ApiV1alpha1MiniClusterSpec(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'containers': ([ApiV1alpha1MiniClusterContainer],),  # noqa: E501
            'cleanup': (bool,),  # noqa: E501
            'deadline_seconds': (int,),  # noqa: E501
            'flux_restful': (ApiV1alpha1FluxRestful,),  # noqa: E501
            'job_labels': ({str: (str,)},),  # noqa: E501
            'logging': (ApiV1alpha1LoggingSpec,),  # noqa: E501
            'pod': (ApiV1alpha1PodSpec,),  # noqa: E501
            'size': (int,),  # noqa: E501
            'tasks': (int,),  # noqa: E501
            'users': ([ApiV1alpha1MiniClusterUser],),  # noqa: E501
            'volumes': ({str: (ApiV1alpha1MiniClusterVolume,)},),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'containers': 'containers',  # noqa: E501
        'cleanup': 'cleanup',  # noqa: E501
        'deadline_seconds': 'deadlineSeconds',  # noqa: E501
        'flux_restful': 'fluxRestful',  # noqa: E501
        'job_labels': 'jobLabels',  # noqa: E501
        'logging': 'logging',  # noqa: E501
        'pod': 'pod',  # noqa: E501
        'size': 'size',  # noqa: E501
        'tasks': 'tasks',  # noqa: E501
        'users': 'users',  # noqa: E501
        'volumes': 'volumes',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, containers, *args, **kwargs):  # noqa: E501
        """ApiV1alpha1MiniClusterSpec - a model defined in OpenAPI

        Args:
            containers ([ApiV1alpha1MiniClusterContainer]): Containers is one or more containers to be created in a pod. There should only be one container to run flux with runFlux

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            cleanup (bool): Cleanup the pods and storage when the index broker pod is complete. [optional] if omitted the server will use the default value of False  # noqa: E501
            deadline_seconds (int): Should the job be limited to a particular number of seconds? Approximately one year. This cannot be zero or job won't start. [optional] if omitted the server will use the default value of 0  # noqa: E501
            flux_restful (ApiV1alpha1FluxRestful): [optional]  # noqa: E501
            job_labels ({str: (str,)}): Labels for the job. [optional]  # noqa: E501
            logging (ApiV1alpha1LoggingSpec): [optional]  # noqa: E501
            pod (ApiV1alpha1PodSpec): [optional]  # noqa: E501
            size (int): Size (number of job pods to run, size of minicluster in pods). [optional] if omitted the server will use the default value of 0  # noqa: E501
            tasks (int): Total number of CPUs being run across entire cluster. [optional] if omitted the server will use the default value of 0  # noqa: E501
            users ([ApiV1alpha1MiniClusterUser]): Users of the MiniCluster. [optional]  # noqa: E501
            volumes ({str: (ApiV1alpha1MiniClusterVolume,)}): Volumes accessible to containers from a host. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.containers = containers
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
