apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  # Number of pods to create for MiniCluster
  size: 4

  # suppress all output except for test run
  logging:
    quiet: true
    strict: false

  flux:
    container:
      image: ghcr.io/converged-computing/flux-view-ubuntu:tag-focal

  # kubectl apply -f ./examples/simulations/laghos-demos/minicluster.yaml
  # Then watch logs of the broker pod: kubectl logs -n flux-operator <pod> -f
  containers:
    - image: ghcr.io/rse-ops/laghos:tag-jammy
      workingDir: /workflow/Laghos
      command: ./laghos -p 0 -dim 2 -rs 3 -tf 0.75 -pa -vs 100