apiVersion: flux-framework.org/v1alpha1
kind: MiniCluster
metadata:
  name: flux-sample
  namespace: flux-operator
spec:
  size: 4
  volumes:
    data:
      storageClass: hostpath
      path: /tmp/workflow

  containers:
    - image: ghcr.io/rse-ops/singularity:tag-mamba
      workingDir: /tmp/workflow

      environment:
        PYTHONPATH: /usr/lib/python3.10/site-packages
        TMPDIR: /tmp/workflow/tmp

      ports:
        - 8786
      command: python3 /tmp/workflow/launch.py --workers 4 --cores 2

      # Dask will be submitting flux jobs for us
      launcher: true

      # Start the servers as the flux user so they own it
      commands:
        pre: |
           pip install scikit-learn numpy
           # Install my branch of dask distributed with flux integration
           pip install git+https://github.com/researchapps/dask-jobqueue.git@add/flux-no-cleanup
           pip install dask-ml

      fluxUser:
        name: fluxuser

      volumes:
        data:
          path: /tmp/workflow