apiVersion: flux-framework.org/v1alpha1
kind: MiniCluster
metadata:
  name: flux-sample
  namespace: flux-operator
spec:
  size: 4
  volumes:
    data:
      storageClass: hostpath
      path: /tmp/workflow

  containers:
    - image: ghcr.io/rse-ops/dask-scikit-learn:tag-mamba
      workingDir: /tmp/workflow

      environment:
        PYTHONPATH: /usr/lib/python3.10/site-packages
        TMPDIR: /tmp/workflow/tmp

      ports:
        - 8786
      command: python3 /tmp/workflow/launch.py --workers 4 --cores 2

      # Dask will be submitting flux jobs for us
      launcher: true
      fluxUser:
        name: fluxuser
      volumes:
        data:
          path: /tmp/workflow