apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flux-sample-hpa
spec:
  minReplicas: 2
  maxReplicas: 4
  # This is purposefully set to be really low so it triggers!
  # I need to read more about other metrics we can set
  targetCPUUtilizationPercentage: 2
  scaleTargetRef:
    apiVersion: flux-framework.org/v1alpha2
    kind: MiniCluster
    name: flux-sample