apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  size: 2
  # If we don't set this, we won't be able to go above two
  # and the request for 4 nodes will fail instead of scheduling
  maxSize: 4
  interactive: true

  # This allows us to see zeromq and debug logging
  flux:
    logLevel: 7

    # Declare that this cluster will allow for a bursted cluster
    # It would automatically be named burst-0, but we explicitly set
    # for clarity. The leadBroker is left out because this IS it.
    bursting:
      clusters:
        - size: 4
          name: burst-0

  interactive: true
  logging:
    zeromq: true

  # This is a list because a pod can support multiple containers
  containers:
    - image: rockylinux:9
      workingDir: /tmp/workflow

      # Commands to support installing flux-burst plugins
      commands:
        pre: |
          dnf update && dnf install -y python3-pip
          pip install flux-burst
          pip install flux-burst-gke
          pip install kubescaler[all]

      secrets:
        AWS_ACCESS_KEY_ID:
          name: flux-operator-burst
          key: AWS_ACCESS_KEY_ID

        AWS_SECRET_ACCESS_KEY:
          name: flux-operator-burst
          key: AWS_SECRET_ACCESS_KEY

      # Important! We need to have resource requests for the horizonal autoscaler
      # The Flux Operator doesn't know you want to use it, so it's up to you
      # to provide these if your metric is about CPU
      resources:
        limits:
          cpu: "1"

        requests:
          cpu: "1"
