apiVersion: flux-framework.org/v1alpha1
kind: MiniCluster
metadata:
  name: flux-sample
  namespace: flux-operator
spec:
  # Number of pods to create for MiniCluster
  size: 4
  tasks: 4

  # Job output files will be written here
  volumes:
    data:
      storageClass: hostpath
      path: /tmp/data

  # This is a list because a pod can support multiple containers
  containers:
    - image: ghcr.io/rse-ops/singularity:tag-mamba

      # original command: mpirun -n 4 singularity exec ./mpi.sif /opt/mpitest    
      command: |
        flux filemap map -C /data mpi.sif
        # This skips rank 0, since the file is already there
        flux exec -x 0 -r all flux filemap get -C /data
        flux submit -n 4 --output /tmp/fluxout/job.out --error /tmp/fluxout/job.out --flags waitable singularity exec /data/mpi.sif /opt/mpitest
        # This is important to have so we wait for jobs to finish!
        flux queue idle
        flux filemap unmap

      commands:
        post: sleep infinity
        brokerPre: |
          if [[ ! -e "mpi.sif" ]]; then
              singularity pull mpi.sif oras://ghcr.io/rse-ops/singularity-mpi:mpich
          fi

      workingDir: /data
      cores: 1

      # Output files written here
      volumes:
        data:
          path: /tmp/fluxout

      # Batch, and don't wrap in flux submit (we will do this)
      batch: true
      batchRaw: true

      fluxUser:
        name: fluxuser
       
      # Running a container in a container
      securityContext:
        privileged: true