# coding: utf-8

"""
    fluxoperator

    Python SDK for Flux-Operator

    The version of the OpenAPI document: v1alpha2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class MiniClusterStatus(BaseModel):
    """
    MiniClusterStatus defines the observed state of Flux
    """ # noqa: E501
    conditions: Optional[List[V1Condition]] = Field(default=None, description="conditions hold the latest Flux Job and MiniCluster states")
    jobid: StrictStr = Field(description="The Jobid is set internally to associate to a miniCluster This isn't currently in use, we only have one!")
    maximum_size: StrictInt = Field(description="We keep the original size of the MiniCluster request as this is the absolute maximum", alias="maximumSize")
    selector: StrictStr
    size: StrictInt = Field(description="These are for the sub-resource scale functionality")
    __properties: ClassVar[List[str]] = ["conditions", "jobid", "maximumSize", "selector", "size"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MiniClusterStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in conditions (list)
        _items = []
        if self.conditions:
            for _item in self.conditions:
                if _item:
                    _items.append(_item.to_dict())
            _dict['conditions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MiniClusterStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "conditions": [V1Condition.from_dict(_item) for _item in obj["conditions"]] if obj.get("conditions") is not None else None,
            "jobid": obj.get("jobid") if obj.get("jobid") is not None else '',
            "maximumSize": obj.get("maximumSize") if obj.get("maximumSize") is not None else 0,
            "selector": obj.get("selector") if obj.get("selector") is not None else '',
            "size": obj.get("size") if obj.get("size") is not None else 0
        })
        return _obj


