apiVersion: flux-framework.org/v1alpha1
kind: MiniCluster
metadata:
  name: flux-sample
  namespace: flux-operator
spec:

  # Number of pods to create for MiniCluster
  size: 2

  # Start an interactive broker
  interactive: true

  # The pod needs to use the device manager for fuse, and
  # to select the nodes that have the service account enabled
  pod:
    serviceAccountName: flux-operator-sa
    nodeSelector:
      iam.gke.io/gke-metadata-server-enabled: "true"
      smarter-device-manager : enabled

  # This will allow us to launch from the command line
  interactive: true

  # show all operator output and test run output
  logging:
    quiet: false

  # This is a list because a pod can support multiple containers
  containers:

      # This image has snakemake installed, and although it has data, we will
      # provide it as a volume to the container to demonstrate that (and share it)
    - image: ghcr.io/rse-ops/atacseq-vanilla:app-latest

      # I hope this trickles up to the pod
      resources:
        limits:
          smarter-devices/fuse: 1
          memory: 512Mi
        requests:
          smarter-devices/fuse: 1
          cpu: 10m
          memory: 50Mi
      
      # This is needed so fuse will work
      # Probably there is a better way...
      # https://github.com/kubernetes/kubernetes/issues/7890#issuecomment-766088805
      securityContext:
        privileged: true
      
      # Commands just for workers / broker
      commands:

        # All flux start / broker commands need to be wrapped in fusion
        prefix: fusion

        # See https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/fusion/FusionConfig.groovy#L29
        pre: |
           # We need fusermount
           apt-get update && apt-get install -y fuse
           wget https://fusionfs.seqera.io/releases/pkg/2/1/6/fusion-amd64.tar.gz
           tar -xzvf fusion-amd64.tar.gz 
           mv ./usr/bin/fusion /usr/local/bin/fusion
           # default -mount-point defaults to /fusion
           mkdir -p /fusion

        # This isn't ideal (and someone could tweak to not need root)
        runFluxAsRoot: true
