apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  size: 2

  # If we don't set this, we won't be able to go above two!
  maxSize: 10

  # Interactive will start the broker to shell into
  interactive: true
  
  # This is a list because a pod can support multiple containers
  containers:
    - image: rockylinux:9
      workingDir: /data

      # You can shell in to connect to the broker and issue commands that use CPU
      command: sleep infinity

      # These are volume mounts for the container for config / secrets we've created separately
      # They are only needed by the leader broker, but per the indexed job, we add to all pods
      # This would be a good usecase for JobSet if we ever decide to switch
      # This is an existing secret that we will mount into /etc/certs
      existingVolumes:
        certs:
          path: /etc/certs
          secretName: certs

      # Important! We need to have resource requests for the horizonal autoscaler
      # The Flux Operator doesn't know you want to use it, so it's up to you
      # to provide these if your metric is about CPU
      resources:
        limits:
          cpu: "1"

        requests:
          cpu: "1"
      
      # Install the metrics exporter, ensuring it's installed to the Flux user space
      commands:
        pre: |
          . /mnt/flux/flux-view.sh
          python3.11 -m ensurepip
          python3.11 -m pip install flux-metrics-api