apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:

  # Number of pods to create for MiniCluster
  size: 4
  interactive: true
  flux:
    container:
      image: ghcr.io/converged-computing/flux-view-ubuntu:tag-focal

  containers:

      # This image has snakemake installed, and although it has data, we will
      # provide it as a volume to the container to demonstrate that (and share it)
    - image: ghcr.io/rse-ops/snakemake:python-3.11

      # Mount Google Filestore to our cluster
      # see pvc.yaml for creating this first
      # https://cloud.google.com/filestore/docs/csi-driver#access
      volumes:
        data:
          path: /workflow
          claimName: data 