---
# Source: s3-otomount/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-mounter
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::633731392008:policy/kubernetes-s3-access
---
# Source: s3-otomount/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: s3-mounter
  name: s3-mounter
  namespace: otomount
spec:
  selector:
    matchLabels: 
      app: s3-mounter
  template:
    metadata:
      labels:
        app: s3-mounter
    spec:
      serviceAccountName: s3-mounter
      containers:
      - name: mounter 
        image: otomato/goofys
        #command: ["./goofys", "-f", "somospie", "/tmp/data"]
        command: ["/bin/sh", "-c", "mkdir -p /tmp/data && ./goofys -o allow_other -o nosuid --file-mode 0777 --dir-mode 0777 --uid 0 --gid 0 -f somospie /tmp/data"]        
        securityContext:
          privileged: true
        volumeMounts:
        - name: mntdatas3
          mountPath: /tmp/data:shared
        env:
          - name: S3_BUCKET
            value: somospie
          - name: MOUNT_PATH
            value: /tmp/data
      volumes:
      - name: mntdatas3
        hostPath:
          path: /tmp/data