apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  # Number of pods to create for MiniCluster
  size: 4
  flux:
    container:
      image: ghcr.io/converged-computing/flux-view-ubuntu:tag-jammy

  containers:
    # The container URI to pull (currently needs to be public)
    - image: ghcr.io/rse-ops/sundials:tag-jammy
      workingDir: /opt/spack/var/spack/environments/sunenv/.spack-env/view/examples/sunmatrix/dense
      command: ./test_sunmatrix_dense 10000 10000 1
      commands:
        pre: |
          . /opt/spack/share/spack/setup-env.sh
          spack env activate sunenv