apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  # Number of pods to create for MiniCluster
  size: 4
  interactive: true
  flux:
    container:
      image: ghcr.io/converged-computing/flux-view-ubuntu:tag-focal

  containers:
    # The container URI to pull (currently needs to be public)
    - image: ghcr.io/rse-ops/sundials:tag-latest

      # There are many examples in the environment but they segfault
      # We would also need to source the spack environment, likely in a script
      # And environment would need to write to somewhere writable!
      # . /opt/spack/share/spack/setup-env.sh
      # spack env activate sunenv
      command: singularity exec --pwd /opt/spack/var/spack/environments/sunenv/.spack-env/view/examples/sunmatrix/dense ./sundials.sif ./test_sunmatrix_dense 10000 10000 1
      workingDir: /data

      # This pulls the container (once) by the broker to workingDir /data
      #commands:
      #  pre: spack env load sunenv
      #  brokerPre: |
      #     if [[ ! -e "sundials.sif" ]]; then
      #         singularity pull /data/sundials.sif docker://ghcr.io/rse-ops/sundials:tag-latest
      #     fi