[exec]
imp = "/usr/libexec/flux/flux-imp"

[access]
allow-guest-user = true
allow-root-owner = true

[resource]
path = "/etc/flux/system/R"

[bootstrap]
curve_cert = "/etc/curve/curve.cert"
default_port = 8050
default_bind = "tcp://eth0:%p"
default_connect = "tcp://%h.flux-service.flux-operator.svc.cluster.local:%p"
hosts = [{host="{{ lead_host }}", bind="tcp://eth0:{{ lead_port }}", connect="tcp://{{ lead_host }}:{{ lead_port }}"},
         {host="{{ job_name }}-{% if size == 1 %}0{% else %}[0-{{ size }}]{% endif %}"}]
[archive]
dbpath = "/var/lib/flux/job-archive.sqlite"
period = "1m"
busytimeout = "50s"
