apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  # Number of pods to create for MiniCluster
  size: 4

  # suppress all output except for test run
  logging:
    quiet: true

  flux:
    container:
      image: ghcr.io/converged-computing/flux-view-ubuntu:tag-focal

  containers:
    - image: ghcr.io/rse-ops/maestro-lulesh:tag-jammy

      # You can set the working directory if your container WORKDIR is not correct.
      workingDir: /workflow/study
      command: maestro run -fg ./lulesh-flux.yaml -y

      # Will serve as a laucher to run Flux submits
      launcher: true