apiVersion: v1
kind: PersistentVolume
metadata:

  ownerReferences:
  - apiVersion: flux-framework.org/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: MiniCluster
    name: flux-sample

    # Get from:
    #  kubectl get -n operator-system pod operator-controller-manager-858c9ccfb4-2k79n -o yaml 
    uid: 87b73461-b5fc-4746-a959-e84518096ed4

  # IMPORTANT: this needs to correspond with your volume name "e.g., data" in the minicluster
  name: data
  namespace: flux-operator
  annotations:
    ibm.io/auto-create-bucket: "false"
    ibm.io/auto-delete-bucket: "false"
    ibm.io/bucket: flux-operator-storage
    ibm.io/chunk-size-mb: "40"
    ibm.io/cos-service: ""
    ibm.io/debug-level: warn
    # ibm.io/iam-endpoint: https://private.iam.cloud.ibm.com
    ibm.io/iam-endpoint: https://iam.cloud.ibm.com
    ibm.io/multireq-max: "20"
    ibm.io/parallel-count: "20"
    ibm.io/s3fs-fuse-retry-count: "5"
    ibm.io/secret-name: s3-secret
    ibm.io/secret-namespace: flux-operator
    ibm.io/stat-cache-size: "100000"
    pv.kubernetes.io/provisioned-by: ibm.io/ibmc-s3fs

spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 25Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim

    # IMPORTANT: this must be the name of the volume plus "-claim"
    name: data-claim
    namespace: flux-operator

  flexVolume:
    driver: ibm/ibmc-s3fs
    options:
      access-mode: ReadWriteMany
      bucket: flux-operator-storage
      chunk-size-mb: "16"
      curl-debug: "false"
      debug-level: warn
      iam-endpoint: https://iam.cloud.ibm.com
      # iam-endpoint: https://private.iam.cloud.ibm.com
      kernel-cache: "true"
      multireq-max: "20"
      # object-store-endpoint: https://s3.direct.us-east.cloud-object-storage.appdomain.cloud
      object-store-storage-class: us-east-standard
      parallel-count: "20"
      s3fs-fuse-retry-count: "5"
      stat-cache-size: "100000"
      tls-cipher-suite: AESGCM
    secretRef:
      name: s3-secret
      namespace: flux-operator
  persistentVolumeReclaimPolicy: Delete
  # This is the custom class we made
  storageClassName: ibm-s3-storage
  volumeMode: Filesystem