apiVersion: flux-framework.org/v1alpha1
kind: MiniCluster
metadata:
  name: flux-sample
  namespace: flux-operator
spec:
  # Number of pods to create for MiniCluster
  size: 4

  fluxRestful:
    branch: list-jobs-tweaks

  # Define one or more users for your cluster
  users:
    - name: peenut
    - name: squidward
    - name: avocadosaurus

  containers:
    - image: ghcr.io/flux-framework/flux-restful-api:test
    # Multi-user mode should not have a command
