# coding: utf-8

"""
    fluxoperator

    Python SDK for Flux-Operator  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from fluxoperator.configuration import Configuration


class Network(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'headless_name': 'str',
        'host_network': 'bool'
    }

    attribute_map = {
        'headless_name': 'headlessName',
        'host_network': 'hostNetwork'
    }

    def __init__(self, headless_name='flux-service', host_network=None, local_vars_configuration=None):  # noqa: E501
        """Network - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._headless_name = None
        self._host_network = None
        self.discriminator = None

        if headless_name is not None:
            self.headless_name = headless_name
        if host_network is not None:
            self.host_network = host_network

    @property
    def headless_name(self):
        """Gets the headless_name of this Network.  # noqa: E501

        Name for cluster headless service  # noqa: E501

        :return: The headless_name of this Network.  # noqa: E501
        :rtype: str
        """
        return self._headless_name

    @headless_name.setter
    def headless_name(self, headless_name):
        """Sets the headless_name of this Network.

        Name for cluster headless service  # noqa: E501

        :param headless_name: The headless_name of this Network.  # noqa: E501
        :type headless_name: str
        """

        self._headless_name = headless_name

    @property
    def host_network(self):
        """Gets the host_network of this Network.  # noqa: E501

        HostNetwork uses the host network for the Pod if true  # noqa: E501

        :return: The host_network of this Network.  # noqa: E501
        :rtype: bool
        """
        return self._host_network

    @host_network.setter
    def host_network(self, host_network):
        """Sets the host_network of this Network.

        HostNetwork uses the host network for the Pod if true  # noqa: E501

        :param host_network: The host_network of this Network.  # noqa: E501
        :type host_network: bool
        """

        self._host_network = host_network

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Network):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Network):
            return True

        return self.to_dict() != other.to_dict()
