apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  # Number of pods to create for MiniCluster
  size: 4
  tasks: 4

  # suppress all output except for test run
  logging:
    quiet: false

  # This is a list because a pod can support multiple containers
  containers:
    # The container URI to pull (currently needs to be public)
    - image: ghcr.io/rse-ops/mpich:tag-mamba

      # Note that there are many examples here!
      # flux run -n 4 ./hello_c
      # flux run -n 4 ./hello_cxx
      # flux run -n 4 ./connectivity_c
      # flux run -n 4 ./hello_usempi
      # flux run -n 4 ./ring_c
      # flux run -n 4 ./ring_usempi
      # flux run -n 4 ./ring_mpifh
      command: ./hello_cxx
      workingDir: /opt/ompi
      environment:
        LD_LIBRARY_PATH: /opt/conda/lib
        PYTHONPATH: /opt/conda/lib/python3.10/site-packages