kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: base-pvc
  namespace: flux-operator
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem