apiVersion: flux-framework.org/v1alpha1
kind: MiniCluster
metadata:
  name: flux-sample
  namespace: flux-operator
spec:
  # Number of pods to create for MiniCluster
  size: 4
  tasks: 4

  # Single pod services running ALONGSIDE the cluster
  services:
    - image: ghcr.io/oras-project/registry:latest
      name: registry
      ports:
        - 5000

  # This is a list because a pod can support multiple containers
  containers:
    # The container URI to pull (currently needs to be public)
    - image: ghcr.io/rse-ops/singularity:tag-mamba
      cores: 4

      # How the container will interact with the registry service
      environment: 
        REGISTRY: flux-sample-services.flux-service.flux-operator.svc.cluster.local

      # You can set the working directory if your container WORKDIR is not correct.
      command: singularity exec --pwd /home/flux/examples/reaxff/HNS ./lammps.sif lmp -v x 2 -v y 2 -v z 2 -in in.reaxc.hns -nocite 

      # TODO add an init container to pull and push container once to local registry
      # This pulls the container (once) by the broker to workingDir /data
      commands:
        brokerPre: |
           if [[ ! -e "lammps.sif" ]]; then
               singularity pull lammps.sif docker://ghcr.io/rse-ops/lammps:flux-sched-focal
               oras push $REGISTRY:5000/flux/lammps:latest --artifact-type appliciation/vnd.sylabs.sif.layer.tar lammps.sif  --plain-http                
           fi

        # The worker is going to
        workerPre: |
            while [ ! -f lammps.sif ]
              do
                oras pull $REGISTRY:5000/flux/lammps:latest --plain-http || echo "LAMMPS image is not ready for pull yet..."
                sleep 30
              done

        # This is going to install oras to pull from our registry
        pre: |
          apt-get update && apt-get install -y curl
          VERSION="1.0.0-rc.2"
          curl -LO "https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_linux_amd64.tar.gz"
          mkdir -p oras-install/
          tar -zxf oras_${VERSION}_*.tar.gz -C oras-install/
          sudo mv oras-install/oras /usr/local/bin/
          rm -rf oras_${VERSION}_*.tar.gz oras-install/

      fluxUser:
        name: fluxuser
       
      # Running a container in a container
      securityContext:
        privileged: true