apiVersion: flux-framework.org/v1alpha1
kind: MiniCluster
metadata:
  name: flux-sample
  namespace: flux-operator
spec:
  size: 4
  # ensure the job is launcher to each of the nodes
  # a server will be started on flux-sample-0, otherwise an agent
  tasks: 4
  logging:
    quiet: true

  volumes:
    data:
      storageClass: hostpath
      path: /tmp/workflow

  containers:
    - image: ghcr.io/rse-ops/k3s:tag-focal
      workingDir: /workflow
      command: /bin/bash ./start.sh

      # Doing this for now to try and reproduce docker-compose setup
      commands:
        runFluxAsRoot: true

      # Note that agent/server specific environment is in start.sh
      environment:
        PYTHONPATH: /usr/lib/python3.10/site-packages
        LD_LIBRARY_PATH: /opt/conda/lib

      ports:
      - 6443
      - 8080
      
      volumes:
        data:
          path: /workflow

      # Container flux owner is "fluxuser"
      fluxUser:
        name: fluxuser

      securityContext:
        privileged: true
