---
apiVersion: v1
kind: Service
metadata:
  name: my-echo
spec:
  selector:
    app: my-echo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-echo
  labels:
    app: my-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-echo
  template:
    metadata:
      labels:
        app: my-echo
    spec:
      containers:
      - name: my-echo
        image: docker.io/vanessa/my-echo:latest
        ports:
        - containerPort: 8080
