apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  size: 4
  flux:
    container:
      image: ghcr.io/converged-computing/flux-view-ubuntu:tag-focal

  # This ensures that fluxion is running as a service to the MiniCluster
  services:
    - image: ghcr.io/converged-computing/fluxion:latest
      command: /code/bin/server --host 0.0.0.0
      name: fluxion

  # A required marker from the user that they want multiple runFlux
  # to work. This is considered an advanced use case.
  oversubscribe: true

  containers:

    # This is a faux "queue only" broker container. It will be
    # the interface to which we submit jobs. We install the
    # fluxion library to interact with the corresponding service.
    - image: rockylinux:9
      name: queue
      commands:
        pre: |
          yum install -y git wget
          /mnt/flux/view/bin/python3.11 -m ensurepip
          /mnt/flux/view/bin/python3.11 -m pip install Flask requests rich
          /mnt/flux/view/bin/python3.11 -m pip install -e "git+https://github.com/converged-computing/fluxion.git#egg=fluxion&subdirectory=python/v1"
          wget -O /mnt/flux/view/fluxion_controller.py https://raw.githubusercontent.com/flux-framework/flux-operator/multiple-applications-per-pod/examples/experimental/multiple-applications-per-pod/fluxion_controller.py
          # By the time we get here, the other brokers have started.
          for socket in $(ls /mnt/flux/view/run/flux/)
            do
              echo "Enabling alloc bypass for $socket"
              flux proxy local:///mnt/flux/view/run/flux/$socket flux jobtap load /mnt/flux/view/lib/flux/job-manager/plugins/alloc-bypass.so 
            done

      runFlux: true
      command: /mnt/flux/view/bin/python3.11 /mnt/flux/view/fluxion_controller.py start

      # command: lmp -v x 2 -v y 2 -v z 2 -in in.reaxc.hns -nocite 
    - image: ghcr.io/rse-ops/lammps-matrix:mpich-ubuntu-20.04-amd64
      name: lammps
      workingDir: /opt/lammps/examples/reaxff/HNS
      command: run_interactive_cluster
      runFlux: true

    - image: ghcr.io/converged-computing/metric-ior:latest
      name: ior
      command: run_interactive_cluster
      runFlux: true

    - image: ghcr.io/converged-computing/metric-chatterbug:latest
      name: chatterbug
      command: run_interactive_cluster
      runFlux: true
