apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  # suppress all output except for test run
  logging:
    quiet: false

  # Number of pods to create for MiniCluster
  # Set 4 tasks so hostname runs on each pod
  size: 4
  tasks: 4
  interactive: true
  containers:
    - image: ghcr.io/rse-ops/ramble-gromacs:ubuntu-jammy
      command: /bin/bash /tmp/ramble-on.sh