apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  # suppress all output except for test run
  logging:
    quiet: false

  # Number of pods to create for MiniCluster
  size: 4
  interactive: true
  containers:
    - image: ghcr.io/rse-ops/ramble-gromacs:ubuntu-jammy
      volumes:
        data:
          hostPath: /data
          path: /tmp/workflow