apiVersion: flux-framework.org/v1alpha1
kind: MiniCluster
metadata:
  name: flux-sample
  namespace: flux-operator
spec:
  size: 4

  # The various merlin commands use flux alloc, and also don't hang / wait until 
  # we are done, so they need to be done interactively
  interactive: true

  containers:
    - image: ghcr.io/rse-ops/merlin-demos-certs:merlin
      workingDir: /workflow

      # Container flux owner is "fluxuser"
      fluxUser:
        name: fluxuser

      commands:
        pre: |
          export LD_LIBRARY_PATH=/opt/conda/lib
          export PYTHONPATH=/home/fluxuser/.local/lib/python3.10/site-packages
          sudo chown -R fluxuser .
          merlin example flux_par
          # Update workflow file to remove queue
          cp ./flux_par.yaml ./flux/flux_par.yaml
          # Queue the tasks! Note we have to update the user and HOME
          sudo -u fluxuser -E PATH=$PATH -E PYTHONPATH=$PYTHONPATH -E LD_LIBRARY_PATH=$LD_LIBRARY_PATH -E USER=fluxuser -E HOME=/home/fluxuser /home/fluxuser/.local/bin/merlin run flux/flux_par.yaml