apiVersion: v1
kind: Service
metadata:
  name: custom-metrics-apiserver
  namespace: flux-operator
spec:
  # This says "the service is on the pod with this selector"
  selector:
    api-server: custom-metrics
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443