apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  size: 2
  # If we don't set this, we won't be able to go above two!
  maxSize: 10

  # This is created with the kind-config.yaml
  # You should only need to pull once (the container is pulled to bound volume)
  volumes:
    data:
      storageClass: hostpath
      path: /tmp/workflow

  # Python is an ubuntu base
  flux:
    container:
      image: ghcr.io/converged-computing/flux-view-ubuntu:tag-focal

  # This is a list because a pod can support multiple containers
  containers:
    - image: python

      # Use the same python alongside flux, this is the view location
      command: /mnt/flux/view/bin/python3.11 /data/three_bears.py
      workingDir: /data

      # Launcher is true (and important) so we can watch in the logs
      # otherwise it would run on a specific pod (and we'd have to find it)
      launcher: true
      commands:
        pre: |
          /mnt/flux/view/bin/python3.11 -m ensurepip
          /mnt/flux/view/bin/python3.11 -m pip install kubernetes

      # Container will be pre-pulled here only by the broker
      volumes:
        data:
          path: /data