apiVersion: flux-framework.org/v1alpha1
kind: MiniCluster
metadata:
  name: flux-sample
  namespace: flux-operator
spec:
  size: 2
  # If we don't set this, we won't be able to go above two!
  maxSize: 10

  # This is created with the kind-config.yaml
  # You should only need to pull once (the container is pulled to bound volume)
  volumes:
    data:
      storageClass: hostpath
      path: /tmp/workflow

  # This is a list because a pod can support multiple containers
  containers:
    - image: ghcr.io/rse-ops/singularity:tag-mamba
      command: python /data/three_bears.py
      workingDir: /data

      # Launcher is true (and important) so we can watch in the logs
      # otherwise it would run on a specific pod (and we'd have to find it)
      launcher: true

      # This pulls the container (once) by the broker to workingDir /data
      commands:
        pre: pip install kubernetes

      fluxUser:
        name: fluxuser

      # Container will be pre-pulled here only by the broker
      volumes:
        data:
          path: /data