name: docs flux-operator
on:
  pull_request: []
  push:
    branches: [main]
 
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: gh-pages

    - name: Create conda environment
      run: conda create --quiet -c conda-forge --name fluxdocs sphinx-material

    - name: Generate Docs
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        root=$PWD
        source activate fluxdocs
        git clone https://github.com/flux-framework/flux-operator /tmp/operator
        cd /tmp/operator/docs
        pip install -r requirements.txt
        pip install sphinx_immaterial==0.12.6
        make html
        echo
        echo "ls"
        ls
        echo
        echo "ls _build/html"
        ls _build/html
        mv $root/.git _build/html/.git
        rm -rf $root
        mv /tmp/operator/docs/_build/html $root
        cd ${root}
        echo "ls $root"
        ls .
        touch .nojekyll
        git add .nojekyll || echo "Already added"
        git add .
        ls .

    - name: Deploy 🚀
      if: (github.event_name != 'pull_request')    
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: .
