name: test python flux-operator

on:
  pull_request: []

jobs:
  basic-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Install fluxoperator python sdk
      run: |
        cd ./sdk/python/v1alpha1
        pip install pytest
        pip install -e .
        pip install flux-restful-client
        cd -

    - name: Run basic tests
      run: pytest -xs sdk/python/v1alpha1/test/test_*.py

  test-python-sdk:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # This is a matrix of test commands and containers, MiniKube is assumed to be running
        test: [["python ./sdk/python/v1alpha1/examples/port-forward.py", "ghcr.io/flux-framework/flux-restful-api:latest"],
               ["python ./sdk/python/v1alpha1/examples/state-pending-jobs-minicluster.py", "ghcr.io/flux-framework/flux-restful-api:latest"],
               ["python ./sdk/python/v1alpha1/examples/interactive-submit.py", "ghcr.io/flux-framework/flux-restful-api:latest"],
               ["pytest -xs ./tests/python/test_*.py", "ghcr.io/flux-framework/flux-restful-api:latest"]]

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Install fluxoperator python sdk
      run: |
        cd ./sdk/python/v1alpha1
        pip install pytest
        pip install -e .
        pip install flux-restful-client
        cd -

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.18

    - name: Create k8s Kind Cluster
      run: |
        curl -Lo ./kind "https://kind.sigs.k8s.io/dl/v0.17.0/kind-$(uname)-amd64"
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind      
        # prepares host mount at /tmp/data
        kind create cluster --config ./script/kind-config.yaml

    - name: Create the namespace
      run: kubectl create namespace flux-operator

    - name: Pull Docker Containers
      env:
        container: ${{ matrix.test[1] }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker pull ${container}
        kind load docker-image ${container}
        make
        make install
        make docker-build
        printf "Loading Flux Operator latest image...\n"
        docker pull ghcr.io/flux-framework/flux-operator:latest
        kind load docker-image ghcr.io/flux-framework/flux-operator:latest
        kubectl apply -f ./examples/dist/flux-operator.yaml

    - name: Test ${{ matrix.test[0] }}
      env:
        command: ${{ matrix.test[0] }}
      run: |
        make clean
        echo "Running command: ${command}"
        ${command}