name: test python flux-operator

on:
  pull_request: []

jobs:
  basic-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Install fluxoperator python sdk
      run: |
        cd ./sdk/python/v1alpha1
        pip install pytest
        pip install -e .
        pip install flux-restful-client
        cd -

    - name: Run basic tests
      run: pytest -xs sdk/python/v1alpha1/test/test_*.py

  test-python-sdk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Install fluxoperator python sdk
      run: |
        cd ./sdk/python/v1alpha1
        pip install pytest
        pip install -e .
        pip install flux-restful-client
        cd -

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.18

    - name: Start minikube
      uses: medyagh/setup-minikube

    - name: Create the namespace
      run: kubectl create namespace flux-operator

    - name: Pull Docker Containers to MiniKube
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        minikube ssh docker pull ghcr.io/flux-framework/flux-restful-api:latest
        make
        make install

    - name: Test port-forward example
      run: /bin/bash ./script/test-python.sh python ./sdk/python/v1alpha1/examples/port-forward.py

    - name: Tests in pytest
      run: /bin/bash ./script/test-python.sh python pytest -xs ./tests/python/test_*.py